// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhxmodsajikjmddlzhhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oeG1vZHNhamlram1kZGx6aGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTI5MjAsImV4cCI6MjA1MzM2ODkyMH0.RLroh1x5qafcTXIYy4bi-f8l256SxDE5APNAlhZ23wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);